// <auto-generated />
using System;
using Air_BnB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Air_BnB.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    [Migration("20220106141430_AirBnB")]
    partial class AirBnB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Air_BnB.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Wervereesp",
                            FirstName = "Roy",
                            LastName = "Smit",
                            PassportNumber = "AA000000001",
                            PostalCode = "0212 PS",
                            StreetName = "Pastaweg",
                            StreetNumber = 12
                        },
                        new
                        {
                            Id = 2,
                            City = "Weesperhoof",
                            FirstName = "Karl",
                            LastName = "Koper",
                            PassportNumber = "BB000000002",
                            PostalCode = "2152 LG",
                            StreetName = "LinguiniStraat",
                            StreetNumber = 86
                        },
                        new
                        {
                            Id = 3,
                            City = "Alweershoof",
                            FirstName = "Max",
                            LastName = "Kopersmit",
                            PassportNumber = "CC000000003",
                            PostalCode = "1462 KG",
                            StreetName = "Macaronihof",
                            StreetNumber = 5
                        });
                });

            modelBuilder.Entity("Air_BnB.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Landlords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Pieter",
                            LastName = "Pinda"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Saradin",
                            LastName = "Sombrero"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Stanley",
                            LastName = "Mes"
                        });
                });

            modelBuilder.Entity("Air_BnB.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Almere"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weesp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wervershoof"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Diemen-Zuid"
                        });
                });

            modelBuilder.Entity("Air_BnB.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EndDate = new DateTime(2022, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            StartDate = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Air_BnB.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnedById")
                        .HasColumnType("int");

                    b.Property<int>("PersonAmount")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnedById");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 4,
                            Name = "Kuiltjes Kamer",
                            OwnedById = 1,
                            PersonAmount = 4,
                            PostalCode = "1521 PZ",
                            Price = 450.88999999999999,
                            StreetName = "KuilengrachtStraat",
                            StreetNumber = 63
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 3,
                            Name = "Dorpjes Kamer",
                            OwnedById = 2,
                            PersonAmount = 2,
                            PostalCode = "1152 KG",
                            Price = 180.33000000000001,
                            StreetName = "Dorpweg",
                            StreetNumber = 108
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 5,
                            Name = "Kamer bij de Pontjes",
                            OwnedById = 3,
                            PersonAmount = 1,
                            PostalCode = "1004 AS",
                            Price = 79.989999999999995,
                            StreetName = "Ponterweg",
                            StreetNumber = 13
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 2,
                            Name = "Brinky Kamer(Niet het koekje)",
                            OwnedById = 1,
                            PersonAmount = 2,
                            PostalCode = "1012 AB",
                            Price = 140.5,
                            StreetName = "BrinkStraat",
                            StreetNumber = 160
                        },
                        new
                        {
                            Id = 5,
                            LocationId = 1,
                            Name = "Fruitkamer",
                            OwnedById = 2,
                            PersonAmount = 2,
                            PostalCode = "1326 HA",
                            Price = 90.75,
                            StreetName = "Abrikozenhof",
                            StreetNumber = 4
                        });
                });

            modelBuilder.Entity("Air_BnB.Models.Reservation", b =>
                {
                    b.HasOne("Air_BnB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air_BnB.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Air_BnB.Models.Room", b =>
                {
                    b.HasOne("Air_BnB.Models.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId");

                    b.HasOne("Air_BnB.Models.Landlord", "OwnedBy")
                        .WithMany("Rooms")
                        .HasForeignKey("OwnedById");

                    b.Navigation("Location");

                    b.Navigation("OwnedBy");
                });

            modelBuilder.Entity("Air_BnB.Models.Landlord", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Air_BnB.Models.Location", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
